FROM ubuntu:22.04

RUN apt update && apt upgrade -y && apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && apt update && apt install python3.12 python3.12-dev -y
RUN git clone https://github.com/WebOfTrust/keripy.git
